### ISSUE TITLE
eris-db.js does not currently expose two vital functions which application builders need

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db.js#28]
- [ ] get_block_by_hash
- [ ] get_tx_by_hash

**Comment by ebuchman** [comment]
get_tx_by_hash is not currently possible because we don't even index the txs. the blocks are also only indexed by height, not hash.

this is a conversation we need to have in erisdb land. basically, the reason we don't keep those extra indices is the overhead. im not sure if its something we'll ever merge in tendermint, though we may build tmsp modules for doing it, or possibly allow it to be enabled in core at the config level - the latter is probably the right approach here. would you mind opening the issue in tendermint repo?

**Comment by ebuchman** [comment]
its also something that can be managed by the local proxy server. in fact, it may be nice to build out some simple sql stuff to index transactions and blocks and other salient events. but again, its really a conversation for erisdb, not something the js can do anything about it, unless the js tracks the chain and does the indexing, but that may be asking too much

**Comment by compleatang** [comment]
OK. If this isn't exposed by edb then indeed wrong place for discussion. Will move the issue there.
