### ISSUE TITLE
Fetch Transaction details from chain

### ISSUE THREAD

**Issue by getsachmail** [eris-ltd/eris-db.js#35]
How to fetch transaction from chain, I am using se

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<app.js>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

console.log("sending transaction");
erisdb.txs().send("9F7572BE4E8D3142C0E12C4E6D0A8E10C5D99EB7143F7AECA132F4E3D122415B920148D9EAA7E787D3F0889E0F4B47252FE0ECAA24AB5CA02F2C2B6735C1AC02"
, "ED6469F715EA4E99427402FEA1E45544C814E3A0", 1234567, "C8371465855B9A36A74872A617A6F519EB4FD23A" ,function(error, data){
    if(error)
    {
        throw error;
    }
     console.log(data);
 });

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<output>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
sending transaction
{ tx_hash: '2FE095A815C32E370E138E2BDDA9D82150EA855F',
  creates_contract: 0,
  contract_addr: '' }

How to fetch transaction details for: tx_hash: '2FE095A815C32E370E138E2BDDA9D82150EA855F'

**Comment by suleza** [comment]
We're struggling with this as well. Would be great to have a full block explorer.

**Comment by NodeGuy** [comment]
This is not possible to do today.

**Comment by lsseckman** [comment]
Hey I see this was closed - is this a planned feature and/or where would we look for a workaround?

**Comment by dennismckinnon** [comment]
This is not something the JS libs can support because erisdb does not currently have a method for retrieving this information. As a result its not simply a matter of tying into an unused rpc point. we have to create it at the erisdb level first. Features such as these are being planned for going forward but there is no current timeline for them.

That said... I am curious as to why the original post by @getsachmail was using erisdb.txs.send() directly rather then the eris-contract.js libs which would make it easier for sure as those tie into the transactAndHold which returns data and not a tx hash so querying for the tx is not needed.

**Comment by getsachmail** [comment]
I was exploring erisdb and eris-contract libs to build a use case for business. There was no specific reason for using erisdb insted eris-contract lib.

**Comment by lsseckman** [comment]
eris-contracts.js returns contract state data but not the raw transaction data, right? It sounds like he was going for a specific query of a transaction from the chain.
