### ISSUE TITLE
Figure out how to use mint-client tools with erisdb

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-db.js#7]
@ebuchman and @androlo do you know if this is possible?  It would be of great assistance to have some commandline access into the erisdb template chain we have been using OR hook erisdb into an existing testnet.

**Comment by dennismckinnon** [comment]
I noticed that erisdb was doing something on port 6060. I'm guessing this is the port used for its p2p communication. I was hoping it was running mint-client capable rpc on it. Unfortunately I don't think thats the case :(

**Comment by dennismckinnon** [comment]
So the better route is probably to get an erisdb instance onto ethan's testnet.and use the normal points for mint client. Looking into it now.

**Comment by androlo** [comment]
Long story short - eris-db and bleeding-edge tendermint/minty will never be in sync; nor should they be.

btw. eris-db actually was actually in sync for a few days last week, and still runs on a dev version of Tendermint, but that was only due to very bad planning, and will not happen in the future. For example, it has the 'infinite loop freaking out thing' when transacting to a non-existing account, and some other (game-breaking) bugs as well, such as the key padding thing. It'll stay in until the tx thing has been resolved, though the next update will probably be another dev version since a less buggy develop version is still preferable to keeping it the same.

**Comment by dennismckinnon** [comment]
So I tried quite a bit last week to figure this out. And the main issue is tendermint itself and not the mint client. I could not get tendermint and erisdb to run on the same state simultaneously.

Over all the transaction formats (which is what mintx really handles) is pretty stable.

my suggested solutions are either

A) Make erisdb accept the same RPC requests that tendermint does by default in addition to the fancier ones you have implemented... Honestly not sure if this is practical or not.
B) Make mintx able to RPC to erisdb as an optional mode.

**Comment by ebuchman** [comment]
so the bad account tx thing has been fixed in tendermint. would be good to get that into erisdb. we need to start better version management so we know when erisdb and tendermint dev will and won't be in sync. i would think they should mostly be able to work together, except when tendermint has to introduce an incompatibility

**Comment by dennismckinnon** [comment]
Indeed. Though really having to start up a pure tendermint node on an erisdb created chain is always going to be a big source of headache. So since Tx formats seem *more* stable then tendermint-erisdb compatibility its probably worth with to re-vamp the tools to make them compatible with both Or make erisdb compatible with the existing tools. Not sure what the best method is here.

**Comment by ebuchman** [comment]
i think erisdb should spawn both rpc servers on two different ports and let the client do whatever they want. probably easiest

**Comment by androlo** [comment]
We should have a 'current stable' tag or even fork of tendermint that we use for stable releases, and have a test-net running on that version, then it wouldn't matter if you access that through mint client or eris-db or something else. It'd all be running the same client anyways.

**Comment by dennismckinnon** [comment]
my feeling is that if i have created a local testing chain like HELDB practically speaking i'm not going to want to start up a tendermint node (which requires shutting down erisdb since they both use 6060 for network communication) just so I can use mint tools. I would prefer to just point my existing mint tools to localhost and access it that way. Thats a far better user experience

**Comment by androlo** [comment]
If that's the case, and you just want to access tendermint but using mint client you should be able to just set the RPC address in `config.toml`. I think it's "laddr" or something like that. I don't know if that works since i've never run it from within eris-db myself.

**Comment by androlo** [comment]
That's how you use mint client to communicate with tendermint, just as in the normal case, which answers this question. Closing the issue. If that does not work for some reason then we'll make a new one, because then it's a bug.
